### ISSUE TITLE
Scrapy 1.0.3 - no active project

### ISSUE THREAD

**Issue by aktywnitu** [scrapy/dirbot#15]
Which scrapy version is supported by this example?

**Comment by duttashi** [comment]
I know this answer is very late but maybe it could help someone 
You get this error message because of the following reason;
"You are not in the active project directory" when executing the `crawl spidername` command
Solution: Therefore, you should be in the project directory and then execute the `crawl spidername` command

**Comment by redapple** [comment]
Cleaning up now that this repo is deprecated.
